<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-27T10:06:49 IST" name="Default suite" finished-at="2022-12-27T10:07:22 IST" duration-ms="32780">
    <groups>
    </groups>
    <test started-at="2022-12-27T10:06:49 IST" name="Default test" finished-at="2022-12-27T10:07:22 IST" duration-ms="32780">
      <class name="pom_DDF_TestNG_BaseClass_UtilityClass.TestClass">
        <test-method is-config="true" signature="OpenBrowser()[pri:0, instance:pom_DDF_TestNG_BaseClass_UtilityClass.TestClass@c33b74f]" started-at="2022-12-27T10:06:49 IST" name="OpenBrowser" finished-at="2022-12-27T10:07:13 IST" duration-ms="23238" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenBrowser -->
        <test-method is-config="true" signature="LoginApp()[pri:0, instance:pom_DDF_TestNG_BaseClass_UtilityClass.TestClass@c33b74f]" started-at="2022-12-27T10:07:13 IST" name="LoginApp" finished-at="2022-12-27T10:07:18 IST" duration-ms="5562" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginApp -->
        <test-method signature="Test1()[pri:0, instance:pom_DDF_TestNG_BaseClass_UtilityClass.TestClass@c33b74f]" started-at="2022-12-27T10:07:18 IST" name="Test1" finished-at="2022-12-27T10:07:20 IST" duration-ms="1859" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0,0] but found [TELLSTAR]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0,0] but found [TELLSTAR]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at pom_DDF_TestNG_BaseClass_UtilityClass.TestClass.Test1(TestClass.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method is-config="true" signature="LogoutApp(org.testng.ITestResult)[pri:0, instance:pom_DDF_TestNG_BaseClass_UtilityClass.TestClass@c33b74f]" started-at="2022-12-27T10:07:20 IST" name="LogoutApp" finished-at="2022-12-27T10:07:21 IST" duration-ms="1406" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test1 status=FAILURE method=TestClass.Test1()[pri:0, instance:pom_DDF_TestNG_BaseClass_UtilityClass.TestClass@c33b74f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoutApp -->
        <test-method is-config="true" signature="CloseBrowser()[pri:0, instance:pom_DDF_TestNG_BaseClass_UtilityClass.TestClass@c33b74f]" started-at="2022-12-27T10:07:21 IST" name="CloseBrowser" finished-at="2022-12-27T10:07:22 IST" duration-ms="624" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
      </class> <!-- pom_DDF_TestNG_BaseClass_UtilityClass.TestClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
